//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2024 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import XCTest
import ArgumentParserTestHelpers

final class ColorGenerateDoccReferenceTests: XCTestCase {
  func testEumerableOptionValue() throws {
    try AssertGenerateDoccReference(command: "color", expected: #"""
      <!-- Generated by swift-argument-parser -->

      # color

      ```
      color --fav=<fav> [--second=<second>] [--help]
      ```

      **--fav=\<fav\>:**

      *Your favorite color.*


      **--second=\<second\>:**

      *Your second favorite color.*

      This is optional.


      **--help:**

      *Show help information.*
      """#)
  }
}
