//===----------------------------------------------------------*- swift -*-===//
//
// This source file is part of the Swift Argument Parser open source project
//
// Copyright (c) 2020 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
//
//===----------------------------------------------------------------------===//

#if os(macOS)

import XCTest
import ArgumentParserTestHelpers

final class CountLinesGenerateDoccReferenceTests: XCTestCase {
  func testCountLines() throws {
    guard #available(macOS 12, *) else { return }
    try AssertGenerateDoccReference(command: "count-lines", expected: #"""
      # count-lines

      <!-- Generated by swift-argument-parser -->
      
      ```
      count-lines [<input-file>] [--prefix=<prefix>] [--verbose] [--help]
      ```

      **input-file:**

      *A file to count lines in. If omitted, counts the lines of stdin.*


      **--prefix=\<prefix\>:**

      *Only count lines with this prefix.*


      **--verbose:**

      *Include extra information in the output.*


      **--help:**

      *Show help information.*
      """#)
  }
}

#endif
