//===----------------------------------------------------------*- swift -*-===//
//
// This source file is part of the Swift Argument Parser open source project
//
// Copyright (c) 2020 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
//
//===----------------------------------------------------------------------===//

import XCTest
import ArgumentParserTestHelpers

final class RepeatGenerateDoccReferenceTests: XCTestCase {
  func testMath() throws {
    try AssertGenerateDoccReference(command: "repeat", expected: #"""
      <!-- Generated by swift-argument-parser -->

      # repeat

      ```
      repeat [--count=<count>] [--include-counter] <phrase> [--help]
      ```

      **--count=\<count\>:**

      *The number of times to repeat 'phrase'.*


      **--include-counter:**

      *Include a counter with each repetition.*


      **phrase:**

      *The phrase to repeat.*


      **--help:**

      *Show help information.*
      """#)
  }
}
